### ISSUE TITLE
bug: Scores aren't submitted for players with space at the end of the nickname.

### ISSUE THREAD

**Issue by hzswdef** [osuAkatsuki/bancho.py#429]
### Describe the bug

The score will not submit if the player has space at the end of the nickname, probably issue may cause in other similar cases, but didn't test yet.

### To Reproduce

1. -

### Expected behavior

Submit score.

### bancho.py Version

4.7.2

### Python Version

3.9.X (Default)

**Comment by minisbett** [comment]
How did you even manage to create an account with such an invalid name

**Comment by hzswdef** [comment]
w8, im stupid, i didn't think that might a guweb issue./
2am, im sorry

**Comment by hzswdef** [comment]
> How did you even manage to create an account with such an invalid name

Anyway, that's possible through the osu! client.

![image](https://user-images.githubusercontent.com/89301466/233835977-14b6e3ce-a47e-4a93-b106-657df9dc0230.png)

**Comment by 0i8** [comment]
> How did you even manage to create an account with such an invalid name

regardless of username it still shouldn't produce this issue during score submission

**Comment by tsunyoku** [comment]
this is a weird one to fix - the reason this happens is because osu will append a space to the end of the username on score submission if the client believes the user has supporter privileges (used to catch really shitty supporter cheats) and as bancho.py provides osu!direct to all, every user has these client privileges.

bancho.py trims the trailing space from the username in order to make the name searchable, hence why this occurs. not too sure how we could have both supported, if it’s even worth doing; the first and last character of a username being a space should be (and i believe already is) forbidden

**Comment by tsunyoku** [comment]
oh actually, upon reading i think i have a simple fix. give me like 10 minutes.

**Comment by minisbett** [comment]
> the first and last character of a username being a space should be (and i believe already is) forbidden

I thought so too, that's why I don't get why is error exists

**Comment by minisbett** [comment]
https://github.com/osuAkatsuki/bancho.py/blob/master/app/api/domains/osu.py#L1849 There does not seem to be any check for that
